version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Correct the context path
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend_V2  # Correct the context path
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network

  admin-portal:
    build:
      context: ./admin-portal  # Correct the context path
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
